services:
  app:
    build: ./app
    restart: unless-stopped
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,pillar.madmallards.com"
      DJANGO_DEBUG: "False"
    volumes:
      - ./data:/app/data
    ports:
      - "${APP_BIND_ADDRESS:-127.0.0.1}:${APP_PORT:-8000}:8000"
